#!/usr/bin/env python3
"""BBP fitness check: no hand-authored dependency/execution graphs (R19, R21).

Charter rules:
  R19: Do not maintain a separate hand-authored execution-graph file that
       duplicates the workflow definition.
  R21: Dependency and impact information is generated from code and contracts,
       not authored as a parallel JSON document.

Input: optional argv — zero or more adopter-shaped roots to scan.
  No args → scan hub ROOT.
  With args → each path is scanned.

Output: zero or more `VIOLATION <path> <reason>` lines, then
  `RESULT:MET` or `RESULT:NOT_MET`.

Failure mode: process exit 0 = RESULT:MET (PASS); exit 1 = RESULT:NOT_MET (FAIL).
  Does not swallow exceptions silently — unexpected errors propagate and abort.

Note: The binding matrix is NOT a dependency or impact graph — it is the
requirement index for this practice hub (R21 clarification in charter).
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

SKIP_DIR_NAMES = {
    ".git",
    "node_modules",
    "dist",
    "__pycache__",
    ".venv",
    "venv",
}

FORBIDDEN_FILENAMES = {
    "dependency-graph.json",
    "dependency_graph.json",
    "dependencygraph.json",
    "execution-graph.json",
    "execution_graph.json",
    "executiongraph.json",
    "impact-analysis.json",
    "impact_analysis.json",
    "impactanalysis.json",
    "call-graph.json",
    "call_graph.json",
    "callgraph.json",
}

ALLOWED_GENERATED_MARKERS = {
    "generated",
    "auto-generated",
    "autogenerated",
    "@generated",
    "do not edit",
}


def is_skipped_dir(path: Path) -> bool:
    return any(part in SKIP_DIR_NAMES for part in path.parts)


def is_generated_file(path: Path) -> bool:
    """Check if file has generation markers indicating it's auto-generated."""
    try:
        content = path.read_text(errors="replace")[:2000].lower()
        return any(marker in content for marker in ALLOWED_GENERATED_MARKERS)
    except Exception:
        return False


def rel(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def scan_one(scan_root: Path) -> list[tuple[str, str]]:
    """Return VIOLATION tuples for one root."""
    violations: list[tuple[str, str]] = []
    
    if not scan_root.is_dir():
        return violations
    
    for path in scan_root.rglob("*"):
        if not path.is_file():
            continue
        if is_skipped_dir(path):
            continue
        
        filename_lower = path.name.lower()
        
        if filename_lower in FORBIDDEN_FILENAMES:
            if is_generated_file(path):
                continue
            violations.append((rel(path), "hand-authored graph file"))
        
        if path.suffix == ".json" and filename_lower not in FORBIDDEN_FILENAMES:
            if "graph" in filename_lower or "dependency" in filename_lower or "impact" in filename_lower:
                if "binding-matrix" not in filename_lower:
                    try:
                        content = path.read_text(errors="replace")
                        data = json.loads(content)
                        if isinstance(data, dict):
                            keys = set(str(k).lower() for k in data.keys())
                            graph_indicators = {"nodes", "edges", "dependencies", "callers", "callees"}
                            if keys & graph_indicators and not is_generated_file(path):
                                violations.append((rel(path), "probable hand-authored graph"))
                    except (json.JSONDecodeError, Exception):
                        pass
    
    return violations


def main() -> int:
    scan_roots = (
        [Path(p).resolve() for p in sys.argv[1:]]
        if len(sys.argv) > 1
        else [ROOT]
    )
    
    violations: list[tuple[str, str]] = []
    for scan_root in scan_roots:
        violations.extend(scan_one(scan_root))
    
    seen = set()
    printed = []
    for item in violations:
        if item in seen:
            continue
        seen.add(item)
        printed.append(item)
        path, reason = item
        print(f"VIOLATION {path} {reason}")
    
    if printed:
        print("RESULT:NOT_MET")
        return 1
    print("RESULT:MET")
    return 0


if __name__ == "__main__":
    sys.exit(main())
